modLoader="javafml"
loaderVersion="[43,)"
license="GNU LGPLv3"
issueTrackerURL="https://github.com/adenprince/stone-grinder-mod/issues"

[[mods]]
modId="stonegrinder"
version="${file.jarVersion}"
displayName="Stone Grinder"
displayURL="https://www.curseforge.com/minecraft/mc-mods/stone-grinder"
logoFile="stonegrinder_icon_256x256.png"
credits="pancakes0228: Chinese (Traditional, Taiwan) Translation"
authors="NightfallClosure, ninjakitty844"
description='''
Adds a Grinder block with utility recipes for building blocks.
Unused building materials can be recycled into other blocks, and sand is made renewable.
'''

[[dependencies.stonegrinder]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stonegrinder]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
