modLoader="javafml"
loaderVersion="[43,)"
license="GNU LGPLv3"

[[mods]]
modId="stonegrinder"
version="${file.jarVersion}"
displayName="Stone Grinder"
logoFile="stonegrinder_icon_256x256.png"
authors="NightfallClosure, ninjakitty844"
description='''
Adds a Grinder block with utility recipes for building blocks.
Unused building materials can be recycled into other blocks, and sand is made renewable.
'''

[[dependencies.stonegrinder]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stonegrinder]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
